# Generated by Django 6.0.6 on 2026-06-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Dokumen')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Dokumen')),
                ('kategori', models.CharField(choices=[('Surat', 'Surat'), ('Laporan', 'Laporan'), ('Kontrak', 'Kontrak'), ('Sertifikat', 'Sertifikat'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=50)),
                ('tanggal_upload', models.DateField(verbose_name='Tanggal Upload')),
                ('file', models.FileField(blank=True, null=True, upload_to='dokumen_files/', verbose_name='File Dokumen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['kode'],
            },
        ),
    ]
